services:
  unstructured:
    image:  downloads.unstructured.io/unstructured-io/unstructured-api:latest
    ports:
      - '8000:8000'
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - article-quiz-db:/var/lib/mysql
  dbgate:
    build: docker
    image: dbgate/dbgate:alpine
    ports:
      - 3100:3000

    volumes:
      - dbgate-data:/root/.dbgate
volumes:
  dbgate-data:
  article-quiz-db:
