services:
  unstructured:
    image:  downloads.unstructured.io/unstructured-io/unstructured-api:latest
    restart: always
    ports:
      - '8000:8000'
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
volumes:
  cache:
    driver: local
