services:
  article-quiz:
    container_name: aq-article-quiz
    image: $REGISTRY/$NX_TASK_TARGET_PROJECT:$SHA
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_HOST=$DB_HOST
      - DB_PASSWORD=$DB_PASSWORD
      - CLAUDE_API_KEY=$CLAUDE_API_KEY
    networks:
      - aq-network
  db:
    image: mysql
    restart: always
    container_name: aq-db
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - aq-db-vol:/var/lib/mysql
    networks:
      - aq-network

volumes:
  aq-db-vol:

networks:
  aq-network:
